name: Trigger auto deployment for aw-capp-github-runner

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aw-capp-github-runner-AutoDeployTrigger-bc273faa-d92f-4a37-8ee7-109920c37226.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: awcrtest.azurecr.io
          username: ${{ secrets.AWCAPPGITHUBRUNNER_REGISTRY_USERNAME }}
          password: ${{ secrets.AWCAPPGITHUBRUNNER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: awcrtest.azurecr.io/aw-capp-github-runner:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AWCAPPGITHUBRUNNER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aw-capp-github-runner -g aw-case-rg --server awcrtest.azurecr.io --username  ${{ secrets.AWCAPPGITHUBRUNNER_REGISTRY_USERNAME }} --password ${{ secrets.AWCAPPGITHUBRUNNER_REGISTRY_PASSWORD }}
            az containerapp update -n aw-capp-github-runner -g aw-case-rg --image awcrtest.azurecr.io/aw-capp-github-runner:${{ github.sha }}
