
name: Test workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    # - run: sudo apt-get install azure-cli

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AWCAPPGITHUBRUNNER_AZURE_CREDENTIALS }}

    - name: Storage Public Endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage account show -n awtestsapub --query networkRuleSet
          az storage container create -n awtest2 --account-name awtestsapub

    - name: Storage Private Endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage account show -n awcasesepe1 --query networkRuleSet
          ifconfig | grep inet
          az container show --resource-group aw-case-rg --name awacitest3vnet --query ipAddress.ip --output tsv
          az storage container create -n awtest --account-name awcasesepe1
