
name: Test workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AWCAPPGITHUBRUNNER_AZURE_CREDENTIALS }}

    - name: Storage Public Endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage account show -n accountname --query networkRuleSet
          az storage container create -n awtest2 --account-name awtestsapub

    - name: Storage Private Endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage account show -n accountname --query networkRuleSet
          az storage container create -n awtest --account-name awcasesepe1
